### PR TITLE
Added functionality to minimize previously estimated stories as well as a QR code for sharing to mobiles

### PR DESCRIPTION
**Pull request by faniereynders**
Implemented an accordion to clean-up some space on the screen allowing one to minimize estimation history. Also added the ability to share game to others using a QR code.

### CODE REVIEW

**Comment by Toxantron** [comment]
@faniereynders do you mind if I take your QR-Code solution and move it to [scrumpoker online](https://github.com/Toxantron/scrumonline)?

**Comment by faniereynders** [comment]
@Toxantron please be my guest

**Comment by Toxantron** [comment]
@faniereynders, great. ;-) To be honest I already did because it was such a great addition with so little effort. Feel free to check it out

**Comment by faniereynders** [comment]
Figured :) no worried! It's a great web-app! Would be even better with a
native app?

**Comment by Toxantron** [comment]
Yeah probably, I added it in the [Road Map](https://github.com/Toxantron/scrumonline#road-map) a while ago. Unfortunately I have neither Android nor iOS experience. I am not even a PHP developer, but normally code C#. It started as something for me and my Scrum team and a little project to expand my web-tech horizon. Limited by time I currently only try to make small additions over time and overall try to keep up with the increasing traffic at _+30%_ each month.

**Comment by evert0n** [comment]
@faniereynders I'm sorry I never merged it, in part was because the project it self never fully supported mobile, I do see it as great addition and in part it already works out of the box for mobile. But for now I won't be adding new features.

I do appreciate the time and effort you put sending us this.

**Comment by evert0n** [comment]
@Toxantron I have some opinions regarding your comments in here, but I won't further discuss. I wish you success with your project and begin an open source too, that you can learn more from that.

**Comment by Toxantron** [comment]
@evert0n thank you and sorry for hijacking the issues in your project. I did not know any better place to formally avoid violating copy right.

**Comment by faniereynders** [comment]
@toxantron let's get in touch. Send me your twitter: fanie AT reynders . co
		

		Get Outlook for iOS
	





On Mon, May 29, 2017 at 10:33 AM +0200, "Thomas Fuchs" <notifications@github.com> wrote:












@evert0n thank you and sorry for hijacking the issues in your project. I did not know any better place to formally avoid violating copy right.

**Pull request closed without merging**
